##
FROM ibmjava:8-sdk
RUN apt-get update -y
## Install Anaconda3
RUN apt-get install bzip2
WORKDIR /ins
# ADD  Anaconda3-4.2.0-Linux-x86_64.sh .
RUN wget https://repo.continuum.io/archive/Anaconda3-4.2.0-Linux-x86_64.sh
RUN bash ./Anaconda3-4.2.0-Linux-x86_64.sh -b -p /anaconda3
ENV PATH /anaconda3/bin:${PATH}


WORKDIR /app
CMD ["python", "-V"]
## Install the application...
WORKDIR /app
ADD StreamsSubmit.py .
ADD bluewater/*.py bluewater/
# Running the simulator requires that you 'ADD' the
# simulation files *.json.
ADD containerSimulator/*.py containerSimulator/
# ADD containerSimulator/*.json containerSimulator/

ADD shared/*.py shared/
ADD shared/creds/credential.py shared/creds/

ENV PYTHONPATH "/app/bluewater:/app/containerSimulator:/app/shared:/app/shared/creds"
run pip install streamsx
run pip install streamsx.messagehub
run pip install redis
# Submit the application.
WORKDIR /app
# python StreamsSubmit.py --run mon --jobName magsMon --nameSpace magsMon
CMD [ "python", "StreamsSubmit.py","--run","mon","--jobName","magsMon","--nameSpace","magsMon"]

# If you enable the the simulator, 'ADD' the *.json files (above).
# python StreamsSubmit.py --run simulator --jobName magsSim --nameSpace magsSim
#CMD [ "python", "StreamsSubmit.py","--run","simulator","--jobName","magsSim","--nameSpace","magSim"]









